# You can use keys for your environments(development, test and production) or you can specify 
# keys for specific domain names(e.g. www.mydomain.org, testing.localhost). If a key is supplied for the domain that 
# corresponds to your current domain it will honored over environment keys.
development:
 ABQIAAAA8tXp6YODN8xmL5sFuapMdRTJQa0g3IQ9GZqIMmInSLzwtGDKaBTrBN9PT0adVbZ2TwodjsdFo2uxag
test:
 ABQIAAAA8tXp6YODN8xmL5sFuapMdRTJQa0g3IQ9GZqIMmInSLzwtGDKaBTrBN9PT0adVbZ2TwodjsdFo2uxag
production:
  put_your_production_key_here